# Generated by Django 3.0.7 on 2020-06-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200610_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
