# Generated by Django 3.0.7 on 2020-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.TextField(max_length=5005),
        ),
    ]
