# Generated by Django 3.0.7 on 2020-06-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200609_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='time',
        ),
        migrations.AddField(
            model_name='bug',
            name='closed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
